name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build_library:
    strategy:
      matrix:
        sys:
          - { os: windows-latest, shell: 'msys2 {0}', ext: dll    }
          - { os: ubuntu-latest,  shell: bash,        ext: so     }
          - { os: macos-latest,   shell: bash,        ext: dylib  }

    runs-on: ${{ matrix.sys.os }}

    defaults:
      run:
        shell: ${{ matrix.sys.shell }}

    steps:
    - name: Install dependencies (Ubuntu)
      if: matrix.sys.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install meson libusb-1.0-0 libusb-1.0-0-dev

    - name: Install dependencies (Mac OS)
      if: matrix.sys.os == 'macos-latest'
      run: brew install meson

    - name: Install dependencies (Windows)
      if: matrix.sys.os == 'windows-latest'
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        install: git mingw-w64-ucrt-x86_64-meson mingw-w64-ucrt-x86_64-libusb mingw-w64-ucrt-x86_64-ca-certificates mingw-w64-ucrt-x86_64-python-certifi mingw-w64-ucrt-x86_64-gcc

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure
      run: meson setup builddir

    - name: Build the library
      run: meson compile usbbluetooth -v -C builddir

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: usbbluetooth_${{ matrix.sys.os }}
        path: builddir/src/libusbbluetooth/libusbbluetooth.${{ matrix.sys.ext }}

  # build_bindings:
  #   needs: build_library
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4
  #     with:
  #       fetch-depth: 0

  #   - name: Download artifacts
  #     uses: actions/download-artifact@v4

  #   - name: Install dependencies
  #     run: |
  #       sudo apt-get update
  #       sudo apt-get install meson libusb-1.0-0 libusb-1.0-0-dev python3-build

  #   - name: Copy library
  #     run: cp usbbluetooth_*/*.{so,dll,dylib} src/bindings/python/usbbluetooth/lib/

  #   - name: Configure
  #     run: meson setup builddir

  #   - name: Build python package
  #     run: meson compile usbbluetooth_python -v -C builddir

  #   - name: Upload artifacts
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: usbbluetooth_python
  #       path: builddir/src/bindings/python/*

  release:
    runs-on: ubuntu-latest
    needs: build_library
    if: contains(github.ref, 'refs/tags/v')
    permissions:
      contents: write

    steps:
    - name: Download binaries
      uses: actions/download-artifact@v4

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          usbbluetooth_*/*.so
          usbbluetooth_*/*.dll
          usbbluetooth_*/*.dylib
